### ISSUE TITLE
Log spam (current thread is not owner)

### ISSUE THREAD

**Issue by Felix14-v2** [Jaffe2718/Fabric-Microphone-Text-Input#1]
## Description
Microphone Text Input causes constant spam in the logs with the messages 
`[Thread-5/ERROR]: current thread is not owner`
and
`[Thread-5/ERROR]: Cannot invoke "Object.wait(long)" because "github.jaffe2718.mcmti.client.event.EventHandler.listenThread" is null`.
I can't even use my launchers because their loggers can't handle such an insane amount of messages.

## Info
- Minecraft 1.19.4
- Fabric 0.14.18
- Fabric API 0.76.0
- MidnightLib 1.3.0
- Microphone Text Input 1.1.1

## Logs
[latest.log](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input/files/11174424/latest.log)
[launcher.log](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input/files/11174421/launcher.log)
* [x] tested with the minimum amount of mods

**Comment by Jaffe2718** [comment]
> ## Description
> Microphone Text Input causes constant spam in the logs with the messages `[Thread-5/ERROR]: current thread is not owner` and `[Thread-5/ERROR]: Cannot invoke "Object.wait(long)" because "github.jaffe2718.mcmti.client.event.EventHandler.listenThread" is null`. I can't even use my launchers because their loggers can't handle such an insane amount of messages.
> 
> ## Info
> * Minecraft 1.19.4
> * Fabric 0.14.18
> * Fabric API 0.76.0
> * MidnightLib 1.3.0
> * Microphone Text Input 1.1.1
> 
> ## Logs
> [latest.log](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input/files/11174424/latest.log) [launcher.log](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input/files/11174421/launcher.log)
> 
> * [x]  tested with the minimum amount of mods

Firstly, I apologize for your inability to use the mod properly.

From your `latest.log`, it can be seen that you did not download the acoustic model and did not correctly configure the absolute path of the acoustic model.

`[23:51:41] [Render thread/INFO]: Loading acoustic model from absolute/path/to/your/acoustic/model ...`

The configuration of the absolute path for this acoustic model is default, which means that you have not configured the acoustic model according to your own computer's situation.It is precisely due to the incorrect configuration of the absolute path in the acoustic model that the speech recognition monitoring process constantly attempts to restart and fails.

It seems that your computer's default language is Russian. It is recommended to set the file encoding of the operating system to `UTF-8` for non English languages to avoid garbled code issues.

And in my impression, all 1.1.1 versions of `Microphone Text Input` do not seem to support `Minecraft 1.19.4`, while `Minecraft 1.19.4` is supported by [Microphone Text Input 1.1.2](https://modrinth.com/mod/microphone-text-input/version/1.1.2).

So my solution for you is as follows:

1. Download the corresponding language's acoustic model from [VOSK Models](https://alphacephei.com/vosk/models), for example, your Russian model should download [this](https://alphacephei.com/vosk/models/vosk-model-small-ru-0.22.zip);

2. Extract the acoustic model files from zip file which you have downloaded, for example, for the Russian Language Model, you should extract the entire folder `vosk-model-small-ru-0.22`. Theoretically, the path to extract is arbitrary, but you must remember this path, and it is an absolute path;

3. Configure the absolute path of this acoustic model in the game. You need to find the `Microphone Text Input` in the mod list in the `Mod Menu`, enter the configuration GUI, write the correct absolute path of your acoustic model into the configuration, save the configuration, and restart the game. For more info, you can visit [Microphone Text Input - Minecraft Mod (modrinth.com)](https://modrinth.com/mod/microphone-text-input/) and [How to download acoustic models · Jaffe2718/Fabric-Microphone-Text-Input Wiki (github.com)](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input/wiki/How-to--download-acoustic-models) and [Mod configuration (Basic) · Jaffe2718/Fabric-Microphone-Text-Input Wiki (github.com)](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input/wiki/Mod-configuration-(Basic))

4. If there is a garbled code issue, please set the default language encoding of your operating system to `UTF-8`, see [Text garble and computer encoding problem solving ideas · Jaffe2718/Fabric-Microphone-Text-Input Wiki (github.com)](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input/wiki/Text-garble-and-computer-encoding-problem-solving-ideas);

5. Ensure that your Java has access to the microphone, see [FAQ · Jaffe2718/Fabric-Microphone-Text-Input Wiki (github.com)](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input/wiki/FAQ).

Wishing you a pleasant use😊!
