### ISSUE TITLE
acoustic model not being detected

### ISSUE THREAD

**Issue by edowski** [Jaffe2718/Fabric-Microphone-Text-Input#2]
acoustic model is not getting loaded i tried putting it in .minecraft\versions\fabric-loader-0.14.19-1.19.4\.mcmti\models and i set the path in mod config to \vosk-model-small-en-us-0.15 i tried the unzipped file but it just say that its not found im only using the mod and its dependecies

logs:
[latest.zip](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input/files/11186300/latest.zip)

**Comment by Jaffe2718** [comment]
Your configuration problem is relatively simple.Obviously, you are using the relative path of the acoustic model rather than the absolute path.This can be confirmed by your description and the log file `latest.log`.
What you need to do is use the absolute path of the acoustic model `vosk-model-small-en-us-0.15`, see [Mod configuration (Basic)](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input/wiki/Mod-configuration-(Basic))

**Comment by edowski** [comment]
when i use absolute path it get detected and i can see it saying Recording & Recognizing but nothing get outputed in chat

**Comment by Jaffe2718** [comment]
Sometimes I also encounter this problem because speech recognition is a highly inefficient deep learning algorithm. If your computer performs well, recognition may be faster. After testing, messages may delay up to 1 minute before being sent, especially when the mod is just started. If it exceeds 1 minute, then you need to check if your computer's microphone is working properly and if Java has permission to access the microphone(See [FAQ](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input/wiki/FAQ)).
